using UnityEngine;

namespace MoonBase.Modules
{
    /// <summary>
    /// ScriptableObject defining a placeable base module type.
    /// Create instances via: Right-click in Project → Create → MoonBase → Module Definition
    ///
    /// Each instance represents a *type* of module (Habitat, Solar Array, etc.).
    /// The BaseModule component on a placed prefab holds a reference to this definition.
    /// </summary>
    [CreateAssetMenu(fileName = "New Module Definition",
                     menuName = "MoonBase/Module Definition",
                     order = 1)]
    public class ModuleDefinition : ScriptableObject
    {
        // ── Identity ───────────────────────────────────────────────────────────
        [Header("Identity")]
        [Tooltip("Unique string ID used for save/load. Never change this after saving layouts.")]
        public string moduleTypeId = "module_habitat_01";

        [Tooltip("Human-readable name shown in the UI.")]
        public string moduleName = "Habitat Module";

        [Tooltip("Short description shown in the info panel.")]
        [TextArea(2, 4)]
        public string description = "Pressurized living quarters for crew.";

        [Tooltip("Icon displayed in the module selector toolbar.")]
        public Sprite icon;

        // ── Prefab ─────────────────────────────────────────────────────────────
        [Header("Prefab")]
        [Tooltip("The 3D prefab to instantiate when this module is placed. " +
                 "Must have a BaseModule component attached.")]
        public GameObject prefab;

        [Tooltip("The ghost/preview prefab shown before placement is confirmed. " +
                 "If null, the main prefab is used with a transparent material override.")]
        public GameObject ghostPrefab;

        // ── Footprint ──────────────────────────────────────────────────────────
        [Header("Footprint & Snapping")]
        [Tooltip("Footprint size in meters (X = width, Y = depth). " +
                 "Used to calculate grid snap offsets between adjacent modules.")]
        public Vector2 footprintMeters = new Vector2(10f, 10f);

        [Tooltip("Height of the module in meters. Informational only for now.")]
        public float heightMeters = 5f;

        [Tooltip("Snap offset for the connection tunnel. Adjacent modules will snap " +
                 "so their edges are this far apart (for tunnel gap).")]
        public float snapGapMeters = 0.5f;

        // ── Resources ──────────────────────────────────────────────────────────
        [Header("Power")]
        [Tooltip("Power generated by this module in kilowatts. Solar panels generate; habitats consume.")]
        [Min(0f)]
        public float powerGenerationKW = 0f;

        [Tooltip("Power consumed by this module in kilowatts.")]
        [Min(0f)]
        public float powerConsumptionKW = 5f;

        [Header("Crew")]
        [Tooltip("Number of crew members this module can house. 0 for non-habitat modules.")]
        [Min(0)]
        public int crewCapacity = 0;

        [Header("Resources")]
        [Tooltip("Oxygen production rate in kg/day. 0 for modules that don't produce oxygen.")]
        [Min(0f)]
        public float oxygenProductionKgPerDay = 0f;

        [Tooltip("Water extraction rate in liters/day (for ice mining modules).")]
        [Min(0f)]
        public float waterExtractionLitersPerDay = 0f;

        // ── Placement Rules ────────────────────────────────────────────────────
        [Header("Placement Rules")]
        [Tooltip("Override max slope for this module type. -1 = use global TerrainRaycaster setting.")]
        [Range(-1f, 90f)]
        public float maxSlopeOverrideDegrees = -1f;

        [Tooltip("If true, this module prefers shadowed areas (e.g. ice miners should be in PSRs).")]
        public bool prefersPermanentShadow = false;

        [Tooltip("If true, this module prefers high solar exposure (e.g. solar arrays).")]
        public bool prefersSunlight = false;

        // ── Category ───────────────────────────────────────────────────────────
        [Header("Category")]
        public ModuleCategory category = ModuleCategory.Habitat;

        // ── Editor Helpers ─────────────────────────────────────────────────────
        /// <summary>Returns the effective max slope for placement (respects override).</summary>
        public float GetEffectiveMaxSlope(float globalMaxSlope)
        {
            return maxSlopeOverrideDegrees >= 0f ? maxSlopeOverrideDegrees : globalMaxSlope;
        }

        /// <summary>Quick summary string for debug logging.</summary>
        public override string ToString()
        {
            return $"[{moduleTypeId}] {moduleName} | " +
                   $"Power: +{powerGenerationKW}/-{powerConsumptionKW} kW | " +
                   $"Crew: {crewCapacity}";
        }
    }

    /// <summary>Module category for UI grouping.</summary>
    public enum ModuleCategory
    {
        Habitat,
        Power,
        LifeSupport,
        Mining,
        Infrastructure,
        Science
    }
}
